In [44]:
import pandas as pd

In [45]:
import numpy as np

In [46]:
import collections

In [47]:
import sklearn, sklearn.tree

In [48]:
def transition_matrix(series1, series2, weights=None):
    transition_matrix = pd.crosstab(series1, series2, values=weights, aggfunc=sum if weights is not None else None, normalize='index')
    return transition_matrix
    
def test_transition_matrix():
    d = pd.DataFrame([[1,2,3],[3,4,1],[1,4,1]])
    tm1 = transition_matrix(d[0],d[1])
    tm2 = transition_matrix(d[0],d[1],d[2])
    assert np.allclose(tm1.as_matrix(), np.array([[0.5,0.5],[0.0,1.0]]), rtol=0.001, atol=0)
    assert np.allclose(tm2.as_matrix(), np.array([[0.75,0.25],[0.0,1.0]]), rtol=0.001, atol=0)
    
test_transition_matrix()

In [49]:
df = pd.read_csv("data.csv")

In [50]:
### PROBLEM 1

In [51]:
df["days_delinquent_old_bin"] = pd.cut(df["days_delinquent_old"], bins=[0,1,5,10,30,60,np.inf], include_lowest=True, right=False)

In [52]:
### PROBLEM 1

In [53]:
df["days_delinquent_new_bin"] = pd.cut(df["days_delinquent_new"], bins=[0,1,5,10,30,60,np.inf], include_lowest=True, right=False)

In [54]:
df

,as_of_date,days_delinquent_old,days_delinquent_new,new_outstanding_principal_balance,initial_loan_amount,fico,sales_channel__c,type,current_collection_method,term,lender_payoff,average_bank_balance__c,last_cleared_payment_date,days_delinquent_old_bin,days_delinquent_new_bin
0,2012-11-01,180,180,29383.75,50000,641.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,12,0.00,46445.21,2012-11-01,"[60, inf)","[60, inf)"
1,2012-11-01,9,9,3200.41,10000,631.0,Referral,Loan - Renewal,ACH Pull,6,0.00,1284.07,2012-11-01,"[5, 10)","[5, 10)"
2,2012-11-01,56,75,56207.38,60000,671.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,9,0.00,29415.70,2012-07-30,"[30, 60)","[60, inf)"
3,2012-11-01,19,30,47496.37,50000,626.0,Direct,Loan - New Customer,ACH Pull,6,0.00,61028.12,2012-10-04,"[10, 30)","[30, 60)"
4,2012-11-01,35,54,21012.15,25000,587.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,2046.37,2012-09-07,"[30, 60)","[30, 60)"
5,2012-11-01,12,26,15423.23,20000,706.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,12,0.00,2773.77,2012-11-01,"[10, 30)","[10, 30)"
6,2012-11-01,180,180,1409.18,25000,NaN,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,10393.84,2012-09-17,"[60, inf)","[60, inf)"
7,2012-11-01,1,6,8556.03,10000,654.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,2346.46,2012-10-31,"[1, 5)","[5, 10)"
8,2012-11-01,1,0,809.36,10000,593.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,2262.00,2012-10-31,"[1, 5)","[0, 1)"
9,2012-11-01,46,65,2381.85,15000,537.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,1407.21,3176.13,2012-08-27,"[30, 60)","[60, inf)"
10,2012-11-01,3,6,23345.52,25000,716.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,6,0.00,423.57,2012-11-01,"[1, 5)","[5, 10)"
11,2012-11-01,2,0,20395.49,30000,631.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,2105.21,2012-11-01,"[1, 5)","[0, 1)"
12,2012-11-01,1,0,17000.00,17000,647.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,3905.75,2012-10-31,"[1, 5)","[0, 1)"
13,2012-11-01,47,66,18719.52,20000,541.0,Direct,Loan - New Customer,ACH Pull,6,0.00,5756.67,2012-08-28,"[30, 60)","[60, inf)"
14,2012-11-01,4,9,15000.00,15000,734.0,Direct,Loan - New Customer,ACH Pull,6,0.00,2994.42,2012-10-30,"[1, 5)","[5, 10)"
15,2012-11-01,3,13,58902.55,75000,686.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,12,0.00,15785.22,2012-10-31,"[1, 5)","[10, 30)"
16,2012-11-01,61,80,20000.00,20000,687.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,3291.55,2012-07-11,"[60, inf)","[60, inf)"
17,2012-11-01,29,42,35000.00,35000,584.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,6,8689.75,2072.33,2012-11-01,"[10, 30)","[30, 60)"
18,2012-11-01,61,68,6158.95,17500,611.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,3603.82,2012-11-01,"[60, inf)","[60, inf)"
19,2012-11-01,6,1,3888.58,10000,694.0,Direct,Loan - New Customer,ACH Pull,6,0.00,2833.90,2012-11-01,"[5, 10)","[1, 5)"
20,2012-11-01,2,2,61915.93,75000,648.0,Direct,Loan - New Customer,ACH Pull,12,37500.00,7804.34,2012-11-01,"[1, 5)","[1, 5)"
21,2012-11-01,180,180,15817.58,50000,794.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,9,0.00,15080.60,2012-10-19,"[60, inf)","[60, inf)"
22,2012-11-01,17,33,33000.00,33000,619.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,18,16892.70,4245.33,2012-11-01,"[10, 30)","[30, 60)"
23,2012-11-01,41,60,35000.00,35000,689.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,49921.18,2012-09-04,"[30, 60)","[60, inf)"
24,2012-11-01,21,38,13585.53,35000,696.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,34422.00,2012-10-26,"[10, 30)","[30, 60)"
25,2012-11-01,4,23,8150.82,10000,620.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,2594.94,2012-10-26,"[1, 5)","[10, 30)"
26,2012-11-01,27,0,807.42,12000,589.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,1380.65,2012-10-18,"[10, 30)","[0, 1)"
27,2012-11-01,6,0,6101.18,10000,710.0,Referral,Loan - New Customer,ACH Pull,6,0.00,1132.31,2012-11-01,"[5, 10)","[0, 1)"
28,2012-11-01,1,0,91478.80,100000,735.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,33993.01,2012-11-01,"[1, 5)","[0, 1)"
29,2012-11-01,4,12,20000.00,20000,624.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,12,0.00,1425.57,2012-10-31,"[1, 5)","[10, 30)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,2012-11-01,57,76,6453.42,10000,654.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,3493.52,2012-09-13,"[30, 60)","[60, inf)"
448,2012-11-01,56,75,25612.32,35000,605.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,8333.71,2012-08-13,"[30, 60)","[60, inf)"
449,2012-11-01,9,28,35000.00,35000,683.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,12,0.00,3878.88,2012-10-31,"[5, 10)","[10, 30)"
450,2012-11-01,7,12,26316.51,35000,509.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,17236.00,4931.75,2012-11-01,"[5, 10)","[10, 30)"
451,2012-11-01,11,19,3721.46,12000,595.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,6327.60,2012-11-01,"[10, 30)","[10, 30)"
452,2012-11-01,180,180,22510.35,50000,641.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,12,16840.99,46445.21,2012-11-01,"[60, inf)","[60, inf)"
453,2012-11-01,62,64,7230.36,20000,536.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,11730.96,6213.26,2012-11-01,"[60, inf)","[60, inf)"
454,2012-11-01,1,3,10041.28,15000,625.0,Direct,Loan - New Customer,ACH Pull,6,0.00,2159.63,2012-10-31,"[1, 5)","[1, 5)"
455,2012-11-01,27,37,17960.27,23000,596.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,6,12520.00,3209.72,2012-11-01,"[10, 30)","[30, 60)"
456,2012-11-01,2,8,13978.52,18000,625.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,4447.46,2012-10-30,"[1, 5)","[5, 10)"
457,2012-11-01,29,48,7006.53,10000,683.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,3022.38,2012-09-20,"[10, 30)","[30, 60)"
458,2012-11-01,14,0,714.43,35000,637.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,5632.82,2012-10-31,"[10, 30)","[0, 1)"
459,2012-11-01,5,15,18000.00,18000,606.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,6,0.00,2941.75,2012-11-01,"[5, 10)","[10, 30)"
460,2012-11-01,42,42,19847.95,35000,592.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,10130.56,2012-11-01,"[30, 60)","[30, 60)"
461,2012-11-01,45,64,19577.45,35000,657.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,9,0.00,9448.96,2012-09-06,"[30, 60)","[60, inf)"
462,2012-11-01,17,16,10911.14,25000,536.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,7024.00,2012-11-01,"[10, 30)","[10, 30)"
463,2012-11-01,18,0,3067.39,20000,667.0,Direct,Loan - Renewal,ACH Pull,6,0.00,2758.55,2012-11-01,"[10, 30)","[0, 1)"
464,2012-11-01,17,36,32868.71,35000,658.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,15800.50,2012-10-17,"[10, 30)","[30, 60)"
465,2012-11-01,7,7,11170.08,30000,692.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,9,0.00,13078.80,2012-11-01,"[5, 10)","[5, 10)"
466,2012-11-01,13,13,41509.35,50000,695.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,12,0.00,17441.15,2012-11-01,"[10, 30)","[10, 30)"
467,2012-11-01,61,80,40000.00,40000,689.0,Direct,Loan - New Customer,ACH Pull,6,0.00,13461.46,2012-07-26,"[60, inf)","[60, inf)"
468,2012-11-01,17,36,7771.34,8000,532.0,Referral,Loan - New Customer,ACH Pull,6,0.00,3526.42,2012-10-19,"[10, 30)","[30, 60)"
469,2012-11-01,8,25,7287.10,10000,697.0,Direct,Loan - Renewal,ACH Pull,6,0.00,1785.80,2012-11-01,"[5, 10)","[10, 30)"
470,2012-11-01,4,21,4414.44,15000,717.0,Direct,Loan - New Customer,ACH Pull,6,0.00,15127.40,2012-10-26,"[1, 5)","[10, 30)"
471,2012-11-01,58,77,6890.41,40000,613.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,21526.16,2012-08-13,"[30, 60)","[60, inf)"
472,2012-11-01,1,0,93541.75,100000,645.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,9,0.00,13328.08,2012-11-01,"[1, 5)","[0, 1)"
473,2012-11-01,62,81,14697.31,40000,583.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,38779.38,2012-07-23,"[60, inf)","[60, inf)"
474,2012-11-01,39,58,15000.00,15000,518.0,Direct,Loan - New Customer,ACH Pull,5,0.00,14469.02,2012-09-12,"[30, 60)","[30, 60)"
475,2012-11-01,19,38,9355.63,10000,578.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,2463.21,2012-10-04,"[10, 30)","[30, 60)"
476,2012-11-01,22,41,75000.00,75000,625.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,12,0.00,14640.79,2012-11-01,"[10, 30)","[30, 60)"

In [55]:
transition_matrix(df["days_delinquent_old_bin"], df["days_delinquent_new_bin"])

days_delinquent_new_bin,"[0, 1)","[1, 5)","[5, 10)","[10, 30)","[30, 60)","[60, inf)"
days_delinquent_old_bin,,,,,,
"[0, 1)",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
"[1, 5)",0.212598,0.417323,0.118110,0.251969,0.000000,0.000000
"[5, 10)",0.060606,0.030303,0.378788,0.530303,0.000000,0.000000
"[10, 30)",0.080000,0.000000,0.016000,0.376000,0.528000,0.000000
"[30, 60)",0.057143,0.000000,0.000000,0.000000,0.466667,0.476190
"[60, inf)",0.166667,0.000000,0.000000,0.000000,0.000000,0.833333

In [56]:
transition_matrix(df["days_delinquent_old_bin"], df["days_delinquent_new_bin"], df["new_outstanding_principal_balance"])

days_delinquent_new_bin,"[0, 1)","[1, 5)","[5, 10)","[10, 30)","[30, 60)","[60, inf)"
days_delinquent_old_bin,,,,,,
"[0, 1)",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
"[1, 5)",0.187963,0.403151,0.121824,0.287061,0.000000,0.000000
"[5, 10)",0.010089,0.009863,0.425709,0.554338,0.000000,0.000000
"[10, 30)",0.016309,0.000000,0.016963,0.425131,0.541597,0.000000
"[30, 60)",0.008393,0.000000,0.000000,0.000000,0.492230,0.499377
"[60, inf)",0.074384,0.000000,0.000000,0.000000,0.000000,0.925616

In [57]:
transition_matrix(df["days_delinquent_old_bin"], df["days_delinquent_new_bin"], df["fico"])

days_delinquent_new_bin,"[0, 1)","[1, 5)","[5, 10)","[10, 30)","[30, 60)","[60, inf)"
days_delinquent_old_bin,,,,,,
"[0, 1)",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
"[1, 5)",0.208215,0.423840,0.119934,0.248010,0.000000,0.000000
"[5, 10)",0.059469,0.032156,0.380627,0.527748,0.000000,0.000000
"[10, 30)",0.080158,0.000000,0.015796,0.380492,0.523554,0.000000
"[30, 60)",0.054707,0.000000,0.000000,0.000000,0.466289,0.479004
"[60, inf)",0.174686,0.000000,0.000000,0.000000,0.000000,0.825314

In [58]:
df["gain"] = df["days_delinquent_new"] - df["days_delinquent_old"]

In [59]:
df

,as_of_date,days_delinquent_old,days_delinquent_new,new_outstanding_principal_balance,initial_loan_amount,fico,sales_channel__c,type,current_collection_method,term,lender_payoff,average_bank_balance__c,last_cleared_payment_date,days_delinquent_old_bin,days_delinquent_new_bin,gain
0,2012-11-01,180,180,29383.75,50000,641.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,12,0.00,46445.21,2012-11-01,"[60, inf)","[60, inf)",0
1,2012-11-01,9,9,3200.41,10000,631.0,Referral,Loan - Renewal,ACH Pull,6,0.00,1284.07,2012-11-01,"[5, 10)","[5, 10)",0
2,2012-11-01,56,75,56207.38,60000,671.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,9,0.00,29415.70,2012-07-30,"[30, 60)","[60, inf)",19
3,2012-11-01,19,30,47496.37,50000,626.0,Direct,Loan - New Customer,ACH Pull,6,0.00,61028.12,2012-10-04,"[10, 30)","[30, 60)",11
4,2012-11-01,35,54,21012.15,25000,587.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,2046.37,2012-09-07,"[30, 60)","[30, 60)",19
5,2012-11-01,12,26,15423.23,20000,706.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,12,0.00,2773.77,2012-11-01,"[10, 30)","[10, 30)",14
6,2012-11-01,180,180,1409.18,25000,NaN,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,10393.84,2012-09-17,"[60, inf)","[60, inf)",0
7,2012-11-01,1,6,8556.03,10000,654.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,2346.46,2012-10-31,"[1, 5)","[5, 10)",5
8,2012-11-01,1,0,809.36,10000,593.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,2262.00,2012-10-31,"[1, 5)","[0, 1)",-1
9,2012-11-01,46,65,2381.85,15000,537.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,1407.21,3176.13,2012-08-27,"[30, 60)","[60, inf)",19
10,2012-11-01,3,6,23345.52,25000,716.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,6,0.00,423.57,2012-11-01,"[1, 5)","[5, 10)",3
11,2012-11-01,2,0,20395.49,30000,631.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,2105.21,2012-11-01,"[1, 5)","[0, 1)",-2
12,2012-11-01,1,0,17000.00,17000,647.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,3905.75,2012-10-31,"[1, 5)","[0, 1)",-1
13,2012-11-01,47,66,18719.52,20000,541.0,Direct,Loan - New Customer,ACH Pull,6,0.00,5756.67,2012-08-28,"[30, 60)","[60, inf)",19
14,2012-11-01,4,9,15000.00,15000,734.0,Direct,Loan - New Customer,ACH Pull,6,0.00,2994.42,2012-10-30,"[1, 5)","[5, 10)",5
15,2012-11-01,3,13,58902.55,75000,686.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,12,0.00,15785.22,2012-10-31,"[1, 5)","[10, 30)",10
16,2012-11-01,61,80,20000.00,20000,687.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,3291.55,2012-07-11,"[60, inf)","[60, inf)",19
17,2012-11-01,29,42,35000.00,35000,584.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,6,8689.75,2072.33,2012-11-01,"[10, 30)","[30, 60)",13
18,2012-11-01,61,68,6158.95,17500,611.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,3603.82,2012-11-01,"[60, inf)","[60, inf)",7
19,2012-11-01,6,1,3888.58,10000,694.0,Direct,Loan - New Customer,ACH Pull,6,0.00,2833.90,2012-11-01,"[5, 10)","[1, 5)",-5
20,2012-11-01,2,2,61915.93,75000,648.0,Direct,Loan - New Customer,ACH Pull,12,37500.00,7804.34,2012-11-01,"[1, 5)","[1, 5)",0
21,2012-11-01,180,180,15817.58,50000,794.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,9,0.00,15080.60,2012-10-19,"[60, inf)","[60, inf)",0
22,2012-11-01,17,33,33000.00,33000,619.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,18,16892.70,4245.33,2012-11-01,"[10, 30)","[30, 60)",16
23,2012-11-01,41,60,35000.00,35000,689.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,49921.18,2012-09-04,"[30, 60)","[60, inf)",19
24,2012-11-01,21,38,13585.53,35000,696.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,34422.00,2012-10-26,"[10, 30)","[30, 60)",17
25,2012-11-01,4,23,8150.82,10000,620.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,2594.94,2012-10-26,"[1, 5)","[10, 30)",19
26,2012-11-01,27,0,807.42,12000,589.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,1380.65,2012-10-18,"[10, 30)","[0, 1)",-27
27,2012-11-01,6,0,6101.18,10000,710.0,Referral,Loan - New Customer,ACH Pull,6,0.00,1132.31,2012-11-01,"[5, 10)","[0, 1)",-6
28,2012-11-01,1,0,91478.80,100000,735.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,33993.01,2012-11-01,"[1, 5)","[0, 1)",-1
29,2012-11-01,4,12,20000.00,20000,624.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,12,0.00,1425.57,2012-10-31,"[1, 5)","[10, 30)",8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,2012-11-01,57,76,6453.42,10000,654.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,3493.52,2012-09-13,"[30, 60)","[60, inf)",19
448,2012-11-01,56,75,25612.32,35000,605.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,8333.71,2012-08-13,"[30, 60)","[60, inf)",19
449,2012-11-01,9,28,35000.00,35000,683.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,12,0.00,3878.88,2012-10-31,"[5, 10)","[10, 30)",19
450,2012-11-01,7,12,26316.51,35000,509.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,17236.00,4931.75,2012-11-01,"[5, 10)","[10, 30)",5
451,2012-11-01,11,19,3721.46,12000,595.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,6327.60,2012-11-01,"[10, 30)","[10, 30)",8
452,2012-11-01,180,180,22510.35,50000,641.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,12,16840.99,46445.21,2012-11-01,"[60, inf)","[60, inf)",0
453,2012-11-01,62,64,7230.36,20000,536.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,11730.96,6213.26,2012-11-01,"[60, inf)","[60, inf)",2
454,2012-11-01,1,3,10041.28,15000,625.0,Direct,Loan - New Customer,ACH Pull,6,0.00,2159.63,2012-10-31,"[1, 5)","[1, 5)",2
455,2012-11-01,27,37,17960.27,23000,596.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,6,12520.00,3209.72,2012-11-01,"[10, 30)","[30, 60)",10
456,2012-11-01,2,8,13978.52,18000,625.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,4447.46,2012-10-30,"[1, 5)","[5, 10)",6
457,2012-11-01,29,48,7006.53,10000,683.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,3022.38,2012-09-20,"[10, 30)","[30, 60)",19
458,2012-11-01,14,0,714.43,35000,637.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,5632.82,2012-10-31,"[10, 30)","[0, 1)",-14
459,2012-11-01,5,15,18000.00,18000,606.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,6,0.00,2941.75,2012-11-01,"[5, 10)","[10, 30)",10
460,2012-11-01,42,42,19847.95,35000,592.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,10130.56,2012-11-01,"[30, 60)","[30, 60)",0
461,2012-11-01,45,64,19577.45,35000,657.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,9,0.00,9448.96,2012-09-06,"[30, 60)","[60, inf)",19
462,2012-11-01,17,16,10911.14,25000,536.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,7024.00,2012-11-01,"[10, 30)","[10, 30)",-1
463,2012-11-01,18,0,3067.39,20000,667.0,Direct,Loan - Renewal,ACH Pull,6,0.00,2758.55,2012-11-01,"[10, 30)","[0, 1)",-18
464,2012-11-01,17,36,32868.71,35000,658.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,6,0.00,15800.50,2012-10-17,"[10, 30)","[30, 60)",19
465,2012-11-01,7,7,11170.08,30000,692.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,9,0.00,13078.80,2012-11-01,"[5, 10)","[5, 10)",0
466,2012-11-01,13,13,41509.35,50000,695.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,12,0.00,17441.15,2012-11-01,"[10, 30)","[10, 30)",0
467,2012-11-01,61,80,40000.00,40000,689.0,Direct,Loan - New Customer,ACH Pull,6,0.00,13461.46,2012-07-26,"[60, inf)","[60, inf)",19
468,2012-11-01,17,36,7771.34,8000,532.0,Referral,Loan - New Customer,ACH Pull,6,0.00,3526.42,2012-10-19,"[10, 30)","[30, 60)",19
469,2012-11-01,8,25,7287.10,10000,697.0,Direct,Loan - Renewal,ACH Pull,6,0.00,1785.80,2012-11-01,"[5, 10)","[10, 30)",17
470,2012-11-01,4,21,4414.44,15000,717.0,Direct,Loan - New Customer,ACH Pull,6,0.00,15127.40,2012-10-26,"[1, 5)","[10, 30)",17
471,2012-11-01,58,77,6890.41,40000,613.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,21526.16,2012-08-13,"[30, 60)","[60, inf)",19
472,2012-11-01,1,0,93541.75,100000,645.0,FAP: Managed Application Program,Loan - Renewal,ACH Pull,9,0.00,13328.08,2012-11-01,"[1, 5)","[0, 1)",-1
473,2012-11-01,62,81,14697.31,40000,583.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,38779.38,2012-07-23,"[60, inf)","[60, inf)",19
474,2012-11-01,39,58,15000.00,15000,518.0,Direct,Loan - New Customer,ACH Pull,5,0.00,14469.02,2012-09-12,"[30, 60)","[30, 60)",19
475,2012-11-01,19,38,9355.63,10000,578.0,FAP: Managed Application Program,Loan - New Customer,ACH Pull,6,0.00,2463.21,2012-10-04,"[10, 30)","[30, 60)",19
476,2012-11-01,22,41,75000.00,75000,625.0,FAP: Managed Application Program,Loan - New Customer,Split Funding,12,0.00,14640.79,2012-11-01,"[10, 30)","[30, 60)",19

In [60]:
model = sklearn.tree.DecisionTreeRegressor(max_depth=5)
training_data = df[['average_bank_balance__c', 'new_outstanding_principal_balance', 'initial_loan_amount', 'fico', 'term', 'gain']].dropna()
model.fit(training_data[['average_bank_balance__c', 'new_outstanding_principal_balance', 'initial_loan_amount', 'fico', 'term']], training_data['gain'])

DecisionTreeRegressor(criterion='mse', max_depth=5, max_features=None,
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

In [61]:
model.feature_importances_

array([ 0.01379798,  0.70088777,  0.07625912,  0.20726254,  0.00179259])

In [62]:
sklearn.tree.export_graphviz(model, "tree.dot", )